version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8081:8080'
    volumes:
      - ./app:/srv/app
    working_dir: /srv/app
    command: "yarn run serve"