version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '5555:5555'
    volumes:
      - ./app:/srv/app
    working_dir: /srv/app
    command: "yarn run serve"